//! Snapshot save/restore tests for Linux VMs.
//!
//! Build: cargo test --test snapshot --no-run
//! Then codesign and run manually with --nocapture --test-threads=1

use std::path::PathBuf;
use vfrust::*;

fn image_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap()
        .join("Library/Application Support/ono/images")
}

fn has_images() -> bool {
    image_dir().join("rootfs.raw").exists()
        && image_dir().join("Image").exists()
        && image_dir().join("initrd").exists()
}

fn make_config(
    rootfs: &std::path::Path,
    serial_log: &std::path::Path,
) -> VmConfig {
    VmConfig::builder()
        .cpus(2)
        .memory_mib(512)
        .bootloader(Bootloader::Linux(LinuxBootloader {
            kernel_path: image_dir().join("Image"),
            initrd_path: Some(image_dir().join("initrd")),
            command_line: "console=hvc0 root=/dev/vda rw ip=dhcp net.ifnames=0".into(),
        }))
        .device(Device::VirtioBlk(VirtioBlk {
            path: rootfs.to_path_buf(),
            read_only: false,
            ..Default::default()
        }))
        .device(Device::VirtioNet(VirtioNet {
            attachment: NetAttachment::Nat,
            mac_address: None,
        }))
        .device(Device::VirtioVsock(VirtioVsock {
            port: 1234,
            socket_url: None,
            listen: false,
        }))
        .device(Device::VirtioSerial(VirtioSerial {
            attachment: SerialAttachment::File {
                path: serial_log.to_path_buf(),
            },
        }))
        .device(Device::VirtioRng)
        .build()
        .expect("valid config")
}

fn clone_rootfs(dst: &std::path::Path) {
    let src = image_dir().join("rootfs.raw");
    std::fs::copy(&src, dst).expect("copy rootfs image");
}

/// Same-instance restore: save/restore on the same VM object.
///
/// Uses `snapshot_config()` to rebuild the VM with the resolved machine
/// identifier — required because the save file is bound to it.
#[tokio::test]
async fn test_same_instance_restore() {
    if !has_images() { return; }
    let tmp = tempfile::tempdir().unwrap();
    let rootfs = tmp.path().join("rootfs.raw");
    let save_file = tmp.path().join("vm.vzsave");
    clone_rootfs(&rootfs);

    // Create initial VM (machine identifier auto-generated by VZ)
    let config = make_config(&rootfs, &tmp.path().join("serial.log"));
    let vm = VirtualMachine::new(config).expect("create");
    let h = vm.handle();

    // Capture the snapshot config which has the resolved machine identifier
    let snap_config = h.snapshot_config().clone();

    h.start().await.unwrap();
    tokio::time::sleep(std::time::Duration::from_secs(3)).await;
    h.pause().await.unwrap();
    h.save_state(&save_file).await.unwrap();
    h.stop().await.unwrap();
    drop(vm);

    // Recreate VM from snapshot config (has machine identifier set)
    let vm2 = VirtualMachine::new(snap_config).expect("recreate from snapshot config");
    let h2 = vm2.handle();
    h2.restore_state(&save_file).await.unwrap();
    h2.resume().await.unwrap();
    tokio::time::sleep(std::time::Duration::from_secs(1)).await;
    assert_eq!(h2.state(), VmState::Running);
    h2.stop().await.ok();
}

/// Cross-instance restore using snapshot_config JSON.
///
/// This is the approach the agent uses:
/// 1. Create VM from template (MACs + machine_id auto-generated)
/// 2. Save `snapshot_config().to_json()` (has resolved MACs and machine_id)
/// 3. Save VM state
/// 4. Stop + drop VM
/// 5. Load VmConfig from JSON → create new VM with identical config → restore → resume
#[tokio::test]
async fn test_cross_instance_restore_via_saved_config() {
    if !has_images() { return; }
    let tmp = tempfile::tempdir().unwrap();
    let rootfs = tmp.path().join("rootfs.raw");
    let save_file = tmp.path().join("vm.vzsave");
    let config_file = tmp.path().join("vfrust_config.json");
    clone_rootfs(&rootfs);

    // VM1: create, save config JSON (has auto-populated MACs + machine_id), run, save state
    let config1 = make_config(&rootfs, &tmp.path().join("serial.log"));
    let vm1 = VirtualMachine::new(config1).unwrap();
    let h1 = vm1.handle();

    // Save the snapshot config — it has the real MACs and machine_id resolved by VZ
    let config_json = h1.snapshot_config().to_json().unwrap();
    std::fs::write(&config_file, &config_json).unwrap();

    h1.start().await.unwrap();
    tokio::time::sleep(std::time::Duration::from_secs(3)).await;
    h1.pause().await.unwrap();
    h1.save_state(&save_file).await.unwrap();
    h1.stop().await.unwrap();
    drop(vm1);

    // VM2: load exact config from JSON → create → restore → resume
    let config2 = VmConfig::from_json(&config_file).unwrap();
    let vm2 = VirtualMachine::new(config2).unwrap();
    let h2 = vm2.handle();

    h2.restore_state(&save_file).await.unwrap();
    h2.resume().await.unwrap();
    tokio::time::sleep(std::time::Duration::from_secs(1)).await;
    assert_eq!(h2.state(), VmState::Running);
    h2.stop().await.ok();
}
